name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.3.10'
          - '3.4.8'
          - '4.0.1'

    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        persist-credentials: false

    - name: Set up Ruby
      uses: ruby/setup-ruby@7372622e62b60b3cb750dcd2b9e32c247ffec26a # v1.302.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run tests
      run: bin/test

    - name: Run standardrb
      run: bundle exec standardrb
